version: "3"
services:
  db:
      image: postgres:9.5
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
        - POSTGRES_DB=adminlte
      ports:
        - "5433:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
  web:
    image: ambientum/php:7.1-caddy
    container_name: nasa
    ports:
     - "8081:8080"
    depends_on:
     - db
    volumes:
     - .:/var/www/app
volumes:
  pgdata:
    external: true
